version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: python data_analysis.py orders.csv

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    command: pytest
